---
version: '3.2'
services:
  sendip:
    container_name: sendip
    image: manunkind/sendip:v1.0
    volumes:
      - ${PWD}/config.json:/config.json
    environment:
      MAIL_CONFIG: /config.json
