---
version: '3.2'
services:
  ipsender:
    container_name: ipsender
    image: manunkind/ipsender:v1.0
    volumes:
      - ${PWD}/config.json:/config.json
    environment:
      MAIL_CONFIG: /config.json
