---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sendmail
spec:
  replicas: 1
  minReadySeconds: 1 # Wait 5 seconds after each new pod comes up before marked as "ready"
  strategy:
    type: RollingUpdate # describe how we do rolling updates
    rollingUpdate:
      maxUnavailable: 1 # When updating take one pod down at a time
      maxSurge: 1
  selector:
    matchLabels:
      name: send-mail
  template:
    metadata:
      labels:
        name: send-mail
    spec:
      containers:
      - name: hellogo
        image: manunkind/sendmail:v1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
